-- MySQL Script generated by MySQL Workbench
-- Tue Sep 27 15:37:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sga
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sga` ;

-- -----------------------------------------------------
-- Schema sga
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sga` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sga` ;

-- -----------------------------------------------------
-- Table `sga`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`administrador` (
  `id_administrador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id_administrador`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sga`.`contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`contacto` (
  `id_contacto` INT NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_contacto`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sga`.`domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`domicilio` (
  `id_domicilio` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(45) NULL DEFAULT NULL,
  `no_calle` VARCHAR(45) NULL DEFAULT NULL,
  `pais` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_domicilio`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sga`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`alumno` (
  `id_alumno` INT NOT NULL AUTO_INCREMENT,
  `id_domicilio` INT NULL DEFAULT NULL,
  `id_contacto` INT NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `grado` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_alumno`),
  CONSTRAINT `fk_contacto`
    FOREIGN KEY (`id_contacto`)
    REFERENCES `sga`.`contacto` (`id_contacto`),
  CONSTRAINT `fk_domicilio`
    FOREIGN KEY (`id_domicilio`)
    REFERENCES `sga`.`domicilio` (`id_domicilio`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_domicilio_idx` ON `sga`.`alumno` (`id_domicilio` ASC) VISIBLE;

CREATE INDEX `fk_contacto_idx` ON `sga`.`alumno` (`id_contacto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sga`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `precio` DOUBLE NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sga`.`asignacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`asignacion` (
  `id_asignacion` INT NOT NULL AUTO_INCREMENT,
  `id_alumno` INT NULL DEFAULT NULL,
  `id_curso` INT NULL DEFAULT NULL,
  `turno` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_asignacion`),
  CONSTRAINT `fk_alumno`
    FOREIGN KEY (`id_alumno`)
    REFERENCES `sga`.`alumno` (`id_alumno`),
  CONSTRAINT `fk_curso`
    FOREIGN KEY (`id_curso`)
    REFERENCES `sga`.`curso` (`id_curso`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_alumno_idx` ON `sga`.`asignacion` (`id_alumno` ASC) VISIBLE;

CREATE INDEX `fk_curso_idx` ON `sga`.`asignacion` (`id_curso` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sga`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`comentario` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `nombre_completo` VARCHAR(80) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `comentario` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id_comentario`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
